name: Build Validation

on:
  pull_request:
    branches:
      - main
      - master
      - develop
      - feature/**
      - hotfix/**
      - release/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'ğŸ”„ Checkout cÃ³digo fuente'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'ğŸŸ¢ Configurar Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 'ğŸ·ï¸ Sincronizar etiquetas del Pull Request'
        uses: Maik3345/projex-github-actions/src/pr-label-action@v1
        with:
          pr_number: ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

      - name: 'ğŸ“¦ Instalar pnpm'
        run: npm install -g pnpm

      - name: 'ğŸ“¥ Instalar dependencias'
        run: pnpm install

      - name: 'ğŸ—ï¸ Compilar extensiÃ³n'
        run: npm run build
